feat: github issue form
opensource-f2f/episode pull request #100
Opened 2022-05-10 10:12 UTC by sxzz

2022-05-10 11:52 UTC, kang8 requested changes
非常棒的 PR 👍🏽 ，一些建议。

2022-05-10 11:52 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        推荐格式为 `推荐嘉宾 - [推荐人的姓名/花名/昵称] [栏目]`，栏目可省略；
与 title 同步
```suggestion
        推荐格式为 `推荐嘉宾 - [推荐人的姓名/花名/昵称] （栏目）`，栏目可省略；
```

2022-05-10 11:52 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +
重复
```suggestion
```

2022-05-10 11:52 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - label: 可参考[播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu)准备好录音设备与环境。
这两列作为 `checkboxes` 不太合适。因为该 issue 是推荐者发的，它可能并不知道推荐人是否已订阅邮件列表；是否以准备好录音环境。

建议：放到下方注意栏。

2022-05-10 11:52 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - label: 建议嘉宾[订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)，方便后续发送录制的会议邀请。
鉴于国人使用邮件较少，故添加上注释（事实上在这之前我也不知道该方法）。

> 注：此方法我并没有实践过，只是看到别人说可以，有待证明。

```suggestion
        - label: 建议嘉宾[订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
```

2022-05-10 12:40 UTC, sxzz commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - label: 可参考[播客录音指南](https://www.bilibili.com/video/BV1kq4y1c7Nu)准备好录音设备与环境。
下面的注意栏仅issue填写时可见，所以只能使用checkboxes代替（非必选，不用勾）

2022-05-10 12:43 UTC, sxzz commented
Updated

2022-05-10 13:22 UTC, kang8 approved these changes
👍🏽  LGTM

2022-05-11 05:40 UTC, stevending1st approved these changes
LGTM

2022-05-11 05:43 UTC, LinuxSuRen approved these changes
赞！！！

2022-05-11 05:44 UTC, merged

2022-05-11 05:46 UTC, stevending1st commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - label: 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
```suggestion
        - label: 建议嘉宾 [订阅《开源面对面》的邮件列表](https://groups.google.com/g/osf2f)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
```
替换成 `https://groups.google.com/g/osf2f` 会不会好一些

2022-05-11 05:49 UTC, LinuxSuRen commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - label: 建议嘉宾 [订阅《开源面对面》的邮件列表](mailto:osf2f+subscribe@googlegroups.com)（发送邮件被视为订阅），方便后续发送录制的会议邀请。
https://groups.google.com/g/osf2f 这个地址，有的人可能不太方便访问，但发送邮件没有限制。

2022-05-11 06:07 UTC, juzhiyuan commented on .github/ISSUE_TEMPLATE/recommend_guest.yaml
> +        - Twitter 用于节目录制过程中与嘉宾互动。
with Hyperlink?