# S01E10 李浩然：参与开源要遵循能量守恒
opensource-f2f/episode pull request #101
Opened 2022-05-10 12:27 UTC by LinuxSuRen

音频已经和嘉宾确认过

2022-05-10 14:02 UTC, kang8 commented
Link to #57

2022-05-10 14:13 UTC, kang8 requested changes

2022-05-10 14:13 UTC, kang8 commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +剪辑：Rick
```suggestion
剪辑：[Rick](https://github.com/linuxsuren)（开源爱好者、业余开源布道者）
```

2022-05-10 14:13 UTC, kang8 commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +https://space.bilibili.com/31272861
```suggestion
李浩然的 bilibili 账号：https://space.bilibili.com/31272861
```

2022-05-10 14:13 UTC, kang8 commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +李浩然
或许可以从 issue 中嘉宾的自我介绍中提取出一份简要的介绍放在这里。

Copy from #57
> “李石亮 38岁 大学学习的是文科，编程是个人的兴趣，对操作系统的热爱是理想。在这个领域8年了。现在正式的工作是中小学社团编程老师。自己的事业主要是培养中小学和大学生的人才。自己主要的工作内容是在学习上给他们指导，在就业和职业发展上提供思路和经验上的支持。最重要的是给他们理想，塑造他们的精神世界。让他们明白愚公移山，让他们明白敢叫日月换新天，让他们明白一万年太久，只争朝夕。
> 
> 开源当然是快乐的，但在操作系统这个方向上的压力也是现实的。让年轻人明白中国的操作系统一定要在你们这代人身上实现。你就是那个时代呼唤的人。让他们在大学刚毕业就有这种天下大势，舍我取谁的气魄。这真的发生了，不是我的美好想象，我的学生大四毕业的时候就有这种气魄，我觉得很欣慰，他们没有辜负我们这些人的培养和期待，勇敢的承担起了这个责任。并且不掩饰的表达着。

2022-05-10 14:13 UTC, kang8 commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +* 49:19 - 01:02:57 有眼光 多多思考 那些很冲击你价值观的话
与现有 shownotes 格式保持一致。事实上现有 shownotes 的格式就已经能表达该意思。

比如：
`00:00 嘉宾介绍及如何学习操作系统能通过面试` 就是从 `00:00` 这个时间点开始讨论这个话题。
`15:35 大学生参与开源项目的利弊` 就是从 `15:35` 开始讨论大学生产于开源项目。
也就能反映出 `00:00 - 15:34` 讨论的是嘉宾介绍及如何学习操作系统能通过面试
```suggestion
* 00:00 嘉宾介绍及如何学习操作系统能通过面试
* 15:35 大学生参与开源项目的利弊
* 21:32 能量守恒 开源奉献与自我满足的平衡
* 37:40 企业开源项目需要尊重普通程序员
* 49:19 有眼光 多多思考 那些很冲击你价值观的话
```

2022-05-11 05:41 UTC, LinuxSuRen commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +李浩然
和李老师确认过，他不需要放介绍过来。

2022-05-11 05:44 UTC, LinuxSuRen commented on shownotes/S01E10-李浩然：参与开源要遵循能量守恒.md
> +* 49:19 - 01:02:57 有眼光 多多思考 那些很冲击你价值观的话
![1652247863(1)](https://user-images.githubusercontent.com/1450685/167777122-894970b1-4e27-4943-b5fd-ea7fe6e19d9d.png)

2022-05-11 06:22 UTC, kang8 approved these changes
LGTM

2022-05-13 00:54 UTC, merged