updateS02E13shownote
opensource-f2f/episode pull request #115
Opened 2022-05-28 15:23 UTC by MikeyWei

S02E13 shownote

2022-05-29 01:33 UTC, LinuxSuRen requested changes
文件名需要修改为：`01-开源许可证在国内等于格式合同.md`

2022-05-29 01:33 UTC, LinuxSuRen commented on shownotes/S02E13-开源许可证在国内等于格式合同
> +title: '[番外 01]开源许可证在国内等于格式合同'
建议修改为：`[番外篇 01] 开源许可证在国内等于格式合同`，与其他的保持格式一致

2022-05-29 01:33 UTC, LinuxSuRen commented on shownotes/S02E13-开源许可证在国内等于格式合同
> +num: 'S02E13'
编号应该是01

2022-05-29 01:33 UTC, LinuxSuRen commented on shownotes/S02E13-开源许可证在国内等于格式合同
> +- [Rick](https://github.com/linuxsuren) 开源爱好者、业余开源布道者。
这两句都不是完整的句子，建议不用句号结尾

2022-05-29 01:33 UTC, LinuxSuRen commented on shownotes/S02E13-开源许可证在国内等于格式合同
> +59:25 国产开源协议的意义
感觉“国产”这个词有点别扭，是不是可以考虑用下面的表述：
* 制定（编写）新的中文开源许可证的意义

2022-05-29 01:36 UTC, MikeyWei commented on shownotes/S02E13-开源许可证在国内等于格式合同
> +59:25 国产开源协议的意义
嗯，这样的确更好一些。

2022-05-29 09:54 UTC, kang8 requested changes

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +01:04:27 买卖开源项目时的注意事项
```suggestion
- 00:32 嘉宾介绍
- 02:02 软件著作权、专利与开源许可证的概念
- 03:21 软件著作权与著作权的关系
- 05:48 软件著作权与专利的关系及其保护力
- 11:52 开源许可与软件著作权和专利的关系
- 12:55 网上“开放”代码的大坑
- 14:01 如何定性开源许可证以及它对应的法律是什么
- 16:50 开源两大阵营（FSF & OSI）的介绍
- 20:26 FSF 更注重代码的可复用
- 21:46 OSI 更注重源码可见、并对商业更友好
- 23:36 开源两大阵营的代表性许可证
- 27:41 个人项目如何选择开源许可证
- 29:10 开源作者“删库跑路”后果严重吗
- 31:25 企业项目如何选择开源许可证
- 36:34 切换开源许可证有哪些注意事项
- 44:51 违反开源许可证有哪些后果
- 51:38 开源被侵权时该如何应对
- 59:25 国产开源协议的意义
- 01:04:27 买卖开源项目时的注意事项
```

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +文字修正：
缺少文字修正

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- 2021年9月， [Apache Doris](https://mp.weixin.qq.com/s/QnJ6LFaMOpLasdRpFzGFJA) 与 [DorisDB](https://mp.weixin.qq.com/s/3zHPnPbowIj_OpMIHAobGA) 事件。
格式保持一致
```suggestion
- 2021 年 9 月， [Apache Doris](https://mp.weixin.qq.com/s/QnJ6LFaMOpLasdRpFzGFJA) 与 [DorisDB](https://mp.weixin.qq.com/s/3zHPnPbowIj_OpMIHAobGA) 事件。
```

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- 2021年9月， [Apache Doris](https://mp.weixin.qq.com/s/QnJ6LFaMOpLasdRpFzGFJA) 与 [DorisDB](https://mp.weixin.qq.com/s/3zHPnPbowIj_OpMIHAobGA) 事件。
格式保持一致
```suggestion
- 2021 年 9 月， [Apache Doris](https://mp.weixin.qq.com/s/QnJ6LFaMOpLasdRpFzGFJA) 与 [DorisDB](https://mp.weixin.qq.com/s/3zHPnPbowIj_OpMIHAobGA) 事件。
```

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- 2020 年以来围绕 [PostgreSQL](https://www.postgresql.org/) 商标 PGCAC (PostgreSQL Community Association of Canada) 与 Fundación PostgreSQL 的争执。
> Fundación

Fundación -> Fundation?

Fundación 是法语格式的 Fundation 吗？

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- 2021年[国内首个 GPL 相关判例](https://www.oschina.net/news/159435)，裁判文书网上的[判决书](https://ipc.court.gov.cn/zh-cn/news/view-1823.html)的信息显示，GPL v3协议具有合同性质，是授权方和用户订立的格式化著作权协议。
格式保持一致
```suggestion
- 2021 年[国内首个 GPL 相关判例](https://www.oschina.net/news/159435)，裁判文书网上的[判决书](https://ipc.court.gov.cn/zh-cn/news/view-1823.html)的信息显示，GPL v3 协议具有合同性质，是授权方和用户订立的格式化著作权协议。
```

2022-05-29 09:54 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- Netfilter 内核子系统贡献者 Patrick McHardy 在18个月内成功[滥用版权诉讼“勒索”相关企业200万欧元](https://lore.kernel.org/netdev/Ye6jCQm7z0Yr3bqA@salvia/T/?s=03)但最终和解事件。
格式保持一致
```suggestion
- Netfilter 内核子系统贡献者 Patrick McHardy 在 18 个月内成功[滥用版权诉讼“勒索”相关企业 200 万欧元](https://lore.kernel.org/netdev/Ye6jCQm7z0Yr3bqA@salvia/T/?s=03)但最终和解事件。
```

2022-05-30 03:25 UTC, MikeyWei commented on shownotes/01-开源许可证在国内等于格式合同.md
> +- 2020 年以来围绕 [PostgreSQL](https://www.postgresql.org/) 商标 PGCAC (PostgreSQL Community Association of Canada) 与 Fundación PostgreSQL 的争执。
不确定具体的语种，但不是英语。从新闻里 copy 的这个组织的名字。

2022-05-30 06:05 UTC, kang8 requested changes

2022-05-30 06:05 UTC, kang8 commented on shownotes/01-开源许可证在国内等于格式合同.md
> +hosts: 'Mikey & Rick'
与其他 shownotes 保持一致，加上 link。

https://github.com/opensource-f2f/episode/blob/ad678af025e44a9c4f58802eca2b0ff1d45f5c0e/shownotes/S01E00-%E5%BC%80%E6%BA%90%E9%9D%A2%E5%AF%B9%E9%9D%A2%E8%8A%82%E7%9B%AE%E8%87%AA%E8%BF%B0.md?plain=1#L3-L5

```suggestion
title: '[开源许可证在国内等于格式合同](https://www.ximalaya.com/sound/538384632)'
guests: '振华'
hosts: '[Mikey](https://github.com/MikeyWei) & [Rick](https://github.com/linuxsuren)'
```

2022-05-30 07:52 UTC, kang8 approved these changes
👍 LGMT

2022-05-31 01:33 UTC, LinuxSuRen approved these changes

2022-05-31 01:34 UTC, merged