Submit a draft for a new series - open source community
opensource-f2f/episode pull request #161
Opened 2022-09-08 13:39 UTC by LinuxSuRen

2022-09-20 04:43 UTC, kang8 requested changes

2022-09-20 04:43 UTC, kang8 commented on open-source-community.md
> +* 成立 2 年以上，近 1 年内出于活跃状态
```suggestion
* 成立 2 年以上，近 1 年内处于活跃状态
```

2022-10-19 14:58 UTC, stevending1st commented on open-source-community.md
> +* 资深用户（moderator）
这里为啥要加括号~

2022-10-19 14:58 UTC, stevending1st commented on open-source-community.md
> +* 亲自查看过对应社区的开源项目的 issue、Pull Request 等
```suggestion
* 亲自查看过对应社区的开源项目的 Issue、Pull Request 等
```

2022-10-20 01:00 UTC, LinuxSuRen commented on open-source-community.md
> +* 资深用户（moderator）
括号原本是解释的作用，contributor 这个应该是不太需要括号。我调整下。

2022-10-20 06:33 UTC, stevending1st approved these changes

2022-11-09 02:13 UTC, merged