整理已有的节目系列描述，增加新系列的提议：开源项目访谈
opensource-f2f/episode pull request #42
Opened 2022-02-11 15:35 UTC by LinuxSuRen

2022-02-11 15:36 UTC, LinuxSuRen commented on README.md
> -
自从节目启动以来，除了部分社媒平台在使用 CDF 中文 SIG 的账号外，基本和 CDF 并没有实际的关系。我建议把这部分删除。

2022-02-12 03:14 UTC, kang8 requested changes

2022-02-12 03:14 UTC, kang8 commented on open-source-projects.md
> +* active contributor 数 > 5
其他数据都可以快速的在仓库中找到。对于 active contributor，除了项目的深度参与者，在一个项目中找出 active contributor 似乎不是一件容易的事情。另外，个人认为 active contributor 超过 3 人已经是非常多了。

所以，可以描述下如何在一个项目中找到 active contributor。
或者可以将 active contributor 换成 contributor，该数据相对容易在项目中找到。

2022-02-12 08:02 UTC, kang8 approved these changes

2022-02-12 08:49 UTC, LinuxSuRen commented on open-source-projects.md
> +* active contributor 数 > 5
这里给出的指标仅做参考，不会作为标准。有些数据很容易拿到，但容易拿到的数据有时候也容易“造假”或是“人造”，反而没有可参考性。正如我在文中写到的，这原本就是一个比较“主观”性的判断。我们这个节目并不是要创造流量，或者博人眼球，只是希望能帮助一些有趣的项目。因此，实际执行的条件不会“苛刻“。

2022-02-12 14:00 UTC, kang8 commented on open-source-projects.md
> +* active contributor 数 > 5
了解

2022-02-15 01:21 UTC, juzhiyuan approved these changes
LGTM

2022-02-15 01:21 UTC, juzhiyuan commented on README.md
> +如果你与我们的想法不谋而合，欢迎[加入](member.md)！如果你愿意讲述你的开源故事，欢迎自荐或者推荐周围的朋友。
```suggestion
如果你与我们的想法不谋而合，[欢迎加入](member.md)！如果你愿意讲述你的开源故事，欢迎自荐或者推荐周围的朋友。
```

2022-02-15 01:21 UTC, juzhiyuan commented on open-source-positions.md
> +2021 年，开源在中国似乎像是在井喷式地发展，在商业资本的驱动下，越来越多的企业在以不同形式、程度地支持开源。这对于广大的开源爱好者来说，是一件利好的局面。但是，有非常多的爱好者在利用自己的业余时间参与开源，甚至还不被一些抱有传统观念的团队管理者所认可。
支持开源 社区？项目？

2022-02-15 01:21 UTC, juzhiyuan commented on open-source-positions.md
> +2021 年，开源在中国似乎像是在井喷式地发展，在商业资本的驱动下，越来越多的企业在以不同形式、程度地支持开源。这对于广大的开源爱好者来说，是一件利好的局面。但是，有非常多的爱好者在利用自己的业余时间参与开源，甚至还不被一些抱有传统观念的团队管理者所认可。
是一件利好的事情

2022-02-15 01:27 UTC, wey-gu approved these changes

2022-02-15 01:28 UTC, merged

2022-02-15 01:37 UTC, LinuxSuRen commented on open-source-positions.md
> +2021 年，开源在中国似乎像是在井喷式地发展，在商业资本的驱动下，越来越多的企业在以不同形式、程度地支持开源。这对于广大的开源爱好者来说，是一件利好的局面。但是，有非常多的爱好者在利用自己的业余时间参与开源，甚至还不被一些抱有传统观念的团队管理者所认可。
> 支持开源 社区？项目？

有些企业可能会支持到不仅仅是社区或者项目，可能也会直接直接某个“布道师“。所以，这里的限定语确实可以考虑下。

> 是一件利好的事情

good catch