增加音频文件的原信息文件模板，可以用于 Audacity
opensource-f2f/episode pull request #47
Opened 2022-02-27 10:56 UTC by LinuxSuRen

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1450685/155879582-9e87bbbd-b911-4bbd-a8c9-3a065a0b689f.png">

2022-03-25 03:07 UTC, juzhiyuan submitted a review, later dismissed

2022-03-25 04:18 UTC, kang8 requested changes

2022-03-25 04:18 UTC, kang8 commented on audio-file-metadata-template.xml
> +	<tag name="TITLE" value="StreamNative 开源岗位"/>
既然是 metadata template，是不是可以用更通用的 title？

2022-03-28 01:04 UTC, kang8 approved these changes

2022-03-28 01:10 UTC, merged