第零期 shownotes
opensource-f2f/episode pull request #53
Opened 2022-03-02 06:01 UTC by stevending1st

close https://github.com/opensource-f2f/episode/issues/52

2022-03-02 07:03 UTC, LinuxSuRen requested changes
非常感谢提供 shownotes！赞！

2022-03-02 07:03 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +思为 （Nebula Graph 社区 commiter，vesoft 开发者布道师。siwei.io/about/ ）
我建议把嘉宾放在前面，主播在后面，因为我们的节目是以嘉宾为主，希望大家更关注的也是嘉宾。

主播、主持人的含义非常相似，我个人更倾向于使用主持人。主播感觉上是某个节目的 owner，而这个播客的共建者都是 owner；主持人的话，则表示是某一期主持的人。

2022-03-02 07:03 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +0:00 嘉宾介绍
如果把这里的时间改成下面的格式的话，整体会看起来比较整齐：

`00:00`

2022-03-02 07:58 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +后期：
奥，我误会。后期感觉有点范围大了，是否可以用“剪辑”呢？目前，我们确实没有更多其他的后期制作。

2022-03-02 08:01 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +运营：
运营，目前是没有的。对了，这个 PR 合并后，我们可以基于这个做一个 shownotes 的模板。

2022-03-02 08:02 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +运营：
> 运营，目前是没有的。对了，这个 PR 合并后，我们可以基于这个做一个 shownotes 的模板。

在各个平台分发节目，就是运营

2022-03-02 08:10 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +后期：
> 是否可以用“剪辑”呢？

所以是谁剪的呢

2022-03-02 08:18 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +运营：
下面是百度百科的解释，我还是感觉“运营”这个词太大了。

```
运营就是对运营过程的计划、组织、实施和控制，是与产品生产和服务创造密切相关的各项管理工作的总称。从另一个角度来讲，运营管理也可以指为对生产和提供公司主要的产品和服务的系统进行设计、运行、评价和改进的管理工作。
```

2022-03-02 08:25 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +运营：
> 下面是百度百科的解释，我还是感觉“运营”这个词太大了。
> 
> `运营就是对运营过程的计划、组织、实施和控制，是与产品生产和服务创造密切相关的各项管理工作的总称。从另一个角度来讲，运营管理也可以指为对生产和提供公司主要的产品和服务的系统进行设计、运行、评价和改进的管理工作。`

害，开发者包含很多方面，前端、后端、中台......
听起来是不是很大，你说你是开发者也没错啊

2022-03-02 08:27 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +后期：
是 @wey-gu

2022-03-02 08:31 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +【Staff】
其他地方都是中文，这是不是可以考虑用中文呢

2022-03-02 08:32 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +【Staff】
> 其他地方都是中文，这是不是可以考虑用中文呢

这是通用叫法~

2022-03-03 00:54 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +【Staff】
ok，这里不是 block 建议。

2022-03-03 00:57 UTC, LinuxSuRen requested changes

2022-03-03 00:57 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +运营：Rick
我不太希望自己出现在这里，这个播客节目也不太需要常规意义上的运营，不希望被误解了。

2022-03-03 00:57 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +majinghe（开源爱好者，DevOps 技术布道师）
这里的顺序还是需要调整下，节目的主角是嘉宾而不是主持人。

2022-03-03 01:34 UTC, LinuxSuRen approved these changes

2022-03-03 01:35 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +运营：Rick
> 我不太希望自己出现在这里，这个播客节目也不太需要常规意义上的运营，不希望被误解了。

一个比较好的开源项目应该是每一项工作的贡献者都被记录。

2022-03-03 01:37 UTC, stevending1st commented
这个 shownotes 基于《组织进化论》的格式。

2022-03-03 01:46 UTC, kang8 requested changes
一些建议。另外建议：
* 将 README 中第 0 期标题中的 link 修改成指向本 shownotes。
* 文件名建议修改成 `shownotes/S01E00` 使用以确认的标题来命名。

2022-03-03 01:46 UTC, kang8 commented on shownotes/0-开源面对面节目自述.md
> +【主持人】
既然是用 markdown，就可以用二级标题来标识。如果采纳，请一并修改其他相同地方。
```suggestion
## 主持人
```

2022-03-03 01:46 UTC, kang8 commented on shownotes/0-开源面对面节目自述.md
> +Wey Gu（开源相信者、程序员、图技术 advocate）
可以将嘉宾和主持人添加链接，方便读者与之产生联系。
```suggestion
[Wey Gu](https://github.com/wey-gu)（开源相信者、程序员、图技术 advocate）
```

2022-03-03 01:46 UTC, kang8 commented on shownotes/0-开源面对面节目自述.md
> +开源（open source）：这个词最初是起源于软件开发中，指的是一种开发软件的特殊形式。但到了今天，“开源”已经泛指一组概念——就是我们称之为的“开源的方式”。这些概念包括开源项目、产品，或是自发倡导并欢迎开放变化、协作参与、快速原型、公开透明、精英体制以及面向社区开发的原则。
在行尾添加空行，在 Markdown 中是用空行来分割段落。这样就可以去掉行尾的两个空格。下面句子类似。
```suggestion
开源（open source）：这个词最初是起源于软件开发中，指的是一种开发软件的特殊形式。但到了今天，“开源”已经泛指一组概念——就是我们称之为的“开源的方式”。这些概念包括开源项目、产品，或是自发倡导并欢迎开放变化、协作参与、快速原型、公开透明、精英体制以及面向社区开发的原则。  

```

2022-03-03 01:46 UTC, kang8 commented on shownotes/0-开源面对面节目自述.md
> +Nebula Graph：开源的分布式图数据库。
有官方地址的可以使用超链接的形式。下同。
```suggestion
[Nebula Graph](https://nebula-graph.io/)：开源的分布式图数据库。  
```

2022-03-03 01:58 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +【主持人】
markdown 并不通用, 无法直接在各个平台直接使用，所以用的是纯文本。

2022-03-03 01:59 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +Wey Gu（开源相信者、程序员、图技术 advocate）
同上

2022-03-03 02:00 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +开源（open source）：这个词最初是起源于软件开发中，指的是一种开发软件的特殊形式。但到了今天，“开源”已经泛指一组概念——就是我们称之为的“开源的方式”。这些概念包括开源项目、产品，或是自发倡导并欢迎开放变化、协作参与、快速原型、公开透明、精英体制以及面向社区开发的原则。
同上

2022-03-03 02:01 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +【主持人】
我建议采用 Markdown 的格式，毕竟大家也会在 GitHub 上看到最终提交的效果。另外，现有的播客平台对格式的支持并不好，更新 shownotes 的时候手动调整下就好了。

2022-03-03 02:01 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +Nebula Graph：开源的分布式图数据库。
同上

2022-03-03 02:03 UTC, LinuxSuRen commented
> 这个 shownotes 基于《组织进化论》的格式。

这档节目和《组织进化论》的理念是不同的，我们不会有品牌宣传、商业内容，强调的是通过嘉宾的故事可以帮助到听众，主持人不会有重要的角色。

另外，对于平时接触英文不多的人来说，并不知道 Staff 是什么意思。

如果要参考的话，我倾向于参考一个开源节目的 shownotes。

2022-03-03 02:03 UTC, stevending1st commented
> * 将 README 中第 0 期标题中的 link 修改成指向本 shownotes。

并不建议，这样就没办法看标题点进去听节目了

> * 文件名建议修改成 `shownotes/S01E00` 使用以确认的标题来命名。

已改

2022-03-03 02:06 UTC, LinuxSuRen commented
> 将 README 中第 0 期标题中的 link 修改成指向本 shownotes。

这样是不是就成了“自我指向”了呢？没有太明白具体作用。

2022-03-03 02:07 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +运营：Rick
> 一个比较好的开源项目应该是每一项工作的贡献者都被记录。

我非常同意。

但是，最关键的点在于，我并不认为自己是运营。这个节目也不需要有人来运营。

2022-03-03 02:11 UTC, wey-gu approved these changes
LGTM, Thanks!!!

2022-03-03 02:14 UTC, merged

2022-03-03 02:21 UTC, stevending1st commented
> 另外，对于平时接触英文不多的人来说，并不知道 Staff 是什么意思。

https://www.zhihu.com/question/424726034
 
> 如果要参考的话，我倾向于参考一个开源节目的 shownotes。

其他开源相关节目 shownotes 不太规范。《组织进化论》的 shownotes 有生动活泼参与，应该相对规范。[生动活泼](https://www.qcc.com/product/c5244cce-e2ea-410f-a2cd-7ecf7da41ea7.html)是一家专业的播客公司。

2022-03-03 02:23 UTC, LinuxSuRen commented
我自己知道 Staff 是什么意思，但如果给一个中文词的话，我们所有的目标听众（中文用户）都可以懂了。

2022-03-03 02:27 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +运营：Rick
> 但是，最关键的点在于，我并不认为自己是运营。这个节目也不需要有人来运营。

您做的工作确实是【运营】这个工作中的一部分。

2022-03-03 02:31 UTC, LinuxSuRen commented on shownotes/0-开源面对面节目自述.md
> +运营：Rick
但我本人不这么认为这是一份运营工作，不希望其他人把握当做运营。另外，不在这里展示运营的一个出发点是——不希望强调运营工作，是刻意要弱化运营。节目要自传播。

2022-03-03 02:33 UTC, stevending1st commented on shownotes/0-开源面对面节目自述.md
> +开源（open source）：这个词最初是起源于软件开发中，指的是一种开发软件的特殊形式。但到了今天，“开源”已经泛指一组概念——就是我们称之为的“开源的方式”。这些概念包括开源项目、产品，或是自发倡导并欢迎开放变化、协作参与、快速原型、公开透明、精英体制以及面向社区开发的原则。
> 在行尾添加空行，在 Markdown 中是用空行来分割段落。这样就可以去掉行尾的两个空格。下面句子类似。

并不是一段，而是换一行，分段会有空行，这并不是想见到的。