S01E01
opensource-f2f/episode pull request #58
Opened 2022-03-03 06:42 UTC by stevending1st

close https://github.com/opensource-f2f/episode/issues/54

2022-03-04 05:51 UTC, LinuxSuRen submitted a review, later dismissed

2022-03-04 15:15 UTC, kang8 requested changes
一些建议

2022-03-04 15:15 UTC, kang8 commented on shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
> +**CNCF ambassador**：大使。
```suggestion
**[CNCF ambassador](https://www.cncf.io/people/ambassadors/)**：CNCF 大使。  
```

2022-03-04 15:15 UTC, kang8 commented on shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
> +**[Linux 基金会](https://www.linuxfoundation.org/)**：Linux Foundation，一个非盈利性的联盟，其目的在于协调和推动Linux系统的发展，以及宣传、保护和规范 Linux。
```suggestion
**[Linux 基金会](https://www.linuxfoundation.org/)**：Linux Foundation，一个非盈利性的联盟，其目的在于协调和推动 Linux 系统的发展，以及宣传、保护和规范 Linux。  
```

2022-03-04 15:15 UTC, kang8 commented on shownotes/S01E01-开发者关系 (DevRel) 是开源项目和开源社区的加速器.md
> +**[MongoDB](https://www.mongodb.com/)**：是一个基于分布式文件存储的数据库。由C++语言编写。旨在为WEB应用提供可扩展的高性能数据存储解决方案。
```suggestion
**[MongoDB](https://www.mongodb.com/)**：是一个基于分布式文件存储的数据库。由 C++ 语言编写。旨在为 WEB 应用提供可扩展的高性能数据存储解决方案。  
```

2022-03-05 07:17 UTC, LinuxSuRen approved these changes

2022-03-05 07:18 UTC, merged

2022-03-05 11:17 UTC, LinuxSuRen commented
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1450685/156880782-f0e6bcf3-c1eb-4629-bbdd-c8482eab5511.png">
已更新