增加更多有关嘉宾推荐的描述
opensource-f2f/episode pull request #69
Opened 2022-03-12 01:50 UTC by LinuxSuRen

2022-03-12 02:38 UTC, kang8 requested changes

2022-03-12 02:38 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.md
> +> 注意：建议推荐人先私下得嘉宾同意后再创建 issue 作为正式邀请
```suggestion
> 注意：建议推荐人先私下得到嘉宾同意后再创建 issue 作为正式邀请
```

2022-03-16 13:42 UTC, kang8 approved these changes

2022-03-16 14:30 UTC, wey-gu reviewed
GitHub 也可选？
要不要增加微博、微信公众号？

2022-03-17 01:03 UTC, LinuxSuRen commented
> GitHub 也可选？

+1

> 要不要增加微博、微信公众号？

各种媒体账号有很多的，通常情况下大家也会在自己的账号下做链接的关联。希望有 Twitter 的话，主要为了在 Twitter 上互动。

2022-03-17 03:30 UTC, kang8 requested changes

2022-03-17 03:30 UTC, kang8 commented on .github/ISSUE_TEMPLATE/recommend_guest.md
> +Twitter（可选）:
统一标点为全角
```suggestion
Twitter（可选）：
```

2022-03-21 00:26 UTC, merged