增加：S01E08 小雅：我在读研期间参与 CHAOSS 开源社区的心路经历
opensource-f2f/episode pull request #74
Opened 2022-03-21 09:25 UTC by LinuxSuRen

2022-03-21 09:26 UTC, LinuxSuRen commented
已经和 @xiaoya-Esther 确认过内容以及标题。

2022-03-21 15:57 UTC, wey-gu requested changes

2022-03-23 01:50 UTC, wey-gu approved these changes

2022-03-23 01:50 UTC, wey-gu commented
LGTM, thanks!

2022-03-23 01:50 UTC, merged