S01E09 五花肉的开源运营心得（题目待定）
opensource-f2f/episode pull request #85
Opened 2022-04-20 13:56 UTC by LinuxSuRen

剪辑后的音频文件链接，请查看[这里](https://rkawrngf0e.feishu.cn/file/boxcnGcM8uiEOVbKmt4yNQgzewb)。

See #68

2022-04-21 03:23 UTC, fowse2020 commented
对本期播客标题的建议：
1. 我是这样做开源运营的
2. 开源运营要以“人”为本
3. 运营的本质是锦上添花

2022-04-22 00:56 UTC, LinuxSuRen commented
以下是题目投票结果：

![1be4ca5e58dff7dce051782a0aff34c](https://user-images.githubusercontent.com/1450685/164576053-c23f6186-de49-48f3-b9c5-508b53db94f6.jpg)

2022-04-23 01:02 UTC, kang8 requested changes
Update title(and also need to update file name, because I not have access)

And add hyperlink, make reader easily to find user information.

And a one grammar suggest.

2022-04-25 05:44 UTC, LinuxSuRen commented
感谢 @kang8 @fowse2020 的 comment，已经得到嘉宾的确认，可以发布了。

2022-04-25 05:45 UTC, merged